### PR TITLE
newly added file missing in gemspec

### PR DESCRIPTION
**Pull request by darix**
... and maybe a new gem release

Thank you in advance :)

### CODE REVIEW

**Comment by ppetermann** [comment]
merged and released

**Comment by darix** [comment]
On 2015-04-03 10:26:56 -0700, Peter Petermann wrote:
> merged and released

Are you sure you build the gem with the fixed gemspec?
config.rb is missing in the new gem again.

-- 
           openSUSE - SUSE Linux is my linux
               openSUSE is good for you
                   www.opensuse.org

**Comment by ppetermann** [comment]
usr/bin/ruby2.1 -S gem push pkg/eaal-0.1.15.gem
Pushing gem to https://rubygems.org...
Successfully registered gem: eaal (0.1.15)
disasta@devedge:~/src/eaal $ cat eaal.gemspec|grep config


                                  (master)
  s.files = ["History.txt", "LICENSE.txt", "Manifest.txt", "README.rdoc",
"Rakefile", "lib/eaal.rb", "lib/eaal/api.rb", "lib/eaal/cache/base.rb",
"lib/eaal/cache/file.rb", "lib/eaal/cache/memcached.rb",
"lib/eaal/config.rb", "lib/eaal/exception.rb", "lib/eaal/result.rb",
"lib/eaal/rowset.rb",
"test/fixtures/test/test/account/Characters/Request_.xml",
"test/fixtures/test/test/char/CharacterSheet/Request_.xml",
"test/fixtures/test/test/char/CharacterSheet/Request_characterID_12345.xml",
"test/fixtures/test/test/char/Killlog/Request_.xml",
"test/fixtures/test/test/char/Killlog/Request_characterID_12345.xml",
"test/fixtures/test/test/char/SkillInTraining/Request_characterID_12345.xml",
"test/fixtures/test/test/char/SkillQueue/Request_characterID_12345.xml",
"test/fixtures/test/test/char/Standings/Request_.xml",
"test/fixtures/test/test/char/Standings/Request_characterID_12345.xml",
"test/fixtures/test/test/corp/CorporationSheet/Request_corporationID_150212025.xml",
"test/fixtures/test/test/eve/AllianceList/Request_.xml",
"test/fixtures/test/test/server/ServerStatus/Request_.xml",
"test/test_eaal.rb", "test/test_helper.rb"]


2015-04-03 19:36 GMT+02:00 darix <notifications@github.com>:

> On 2015-04-03 10:26:56 -0700, Peter Petermann wrote:
> > merged and released
>
> Are you sure you build the gem with the fixed gemspec?
> config.rb is missing in the new gem again.
>
> --
> openSUSE - SUSE Linux is my linux
> openSUSE is good for you
> www.opensuse.org
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/3rdpartyeve/eaal/pull/22#issuecomment-89370770>.
>



-- 
Peter Petermann
Email: ppetermann80@gmail.com - get my public PGP key from SKS Keyservers
PGP Key:
http://pool.sks-keyservers.net:11371/pks/lookup?op=get&search=0x0E6DBD675836A5C7

**Comment by ppetermann** [comment]
so yeah, its in there

**Comment by darix** [comment]
On 2015-04-03 10:37:20 -0700, Peter Petermann wrote:
> usr/bin/ruby2.1 -S gem push pkg/eaal-0.1.15.gem
> Pushing gem to https://rubygems.org...
> Successfully registered gem: eaal (0.1.15)
> disasta@devedge:~/src/eaal $ cat eaal.gemspec|grep config

$ gem fetch eaal ; gem unpack *gem ; find eaal-0.1.15 -name config.rb | wc -l
Downloaded eaal-0.1.15
Unpacked gem: '/tmp/eaal-0.1.15'
0

-- 
           openSUSE - SUSE Linux is my linux
               openSUSE is good for you
                   www.opensuse.org

**Comment by ppetermann** [comment]
yah, sorry about that, I haven't been touching this ruby stuff in years. 
the gemspec file is only for if you want to locally build your own gem, when using release the information of the Manifest.txt is used to generate a gemspec (through hoe) on the fly. No one ever added that change to the Manifest, so hoe didn't know its needed. i just released a 0.1.16 that is having its config.rb changes in there.

**Pull request merged**
